version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'maintenance'
    assignees:
      - 'DarkoKukovec'
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'daily'
    labels:
      - 'maintenance'
      - 'documentation'
    assignees:
      - 'DarkoKukovec'
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
