language: node_js
node_js:
  - "10"
  - "12"
env:
  - MOBX_VERSION=4
  - MOBX_VERSION=5
install:
  - npm install -g lerna
  - yarn
  - lerna bootstrap
  - lerna add mobx@${MOBX_VERSION} --dev
  - lerna run build
script:
  - lerna run test
  
deploy:
  provider: script
  script: >
    git config --global user.name "${GH_NAME}";
    git config --global user.email "${GH_EMAIL}";
    echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc;
    cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages;
  on:
    branch: master
