language: node_js
node_js:
  - "8"
  - "10"
  - "11"
env:
  - MOBX_VERSION=4
  - MOBX_VERSION=5
install:
  - npm install -g lerna
  - yarn
  - lerna bootstrap
  - lerna add mobx@${MOBX_VERSION} --dev
  - lerna run build
script: lerna run test
