name: Docs

on:
  push:
    branches: [master, release/*]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup git
        run: |
          git config --global user.name "${{ secrets.DOCS_USER_NAME }}"
          git config --global user.email "${{ secrets.DOCS_USER_EMAIL }}"
          echo "machine github.com login ${{ secrets.DOCS_USER_NAME }} password ${{ secrets.ACCESS_TOKEN }}" > ~/.netrc

      - name: Run & deploy
        run: |
          cd website
          yarn install
          GIT_USER="${{ secrets.DOCS_USER_NAME }}" yarn run publish-gh-pages
