name: Docs

on:
  push:
    branches: [ master, feature/github-action ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: website
          build-command: yarn build
          custom-domain: datx.dev
