name: Lint

on:
  push:
    branches: [master, feature/*, release/*]
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install & run
        run: |
          yarn
          yarn lint --quiet
