name: Unit tests

on:
  push:
    branches: [master, feature/*, release/*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: npm install -g lerna@6
      - run: yarn
      - run: lerna bootstrap
      - run: lerna run build
      - run: lerna run test
